project: "segment_train_org_dataset_8c_128c"
dataset: "../dataset"
logging_dir: "/log"
output_dir: "./output"
enlarge_train_dataset: "../Uncondi_train/enlarge_datasets"
enlarge_and_org_choice: "org" # "enlarge" or "org" or "both"
batch_size: 16
num_epochs: 100
lr: 0.0001
image_size: 256
seed: 7777777
save_dir: "./save_dir"
color_mode: "grayscale" # "rgb" or "grayscale"
resume_from_checkpoint: null # null , "latest", "path/to/checkpoint“
checkpoint_epochs: 10
checkpoints_total_limit: 5